### ISSUE TITLE
create new file if doesn't exits or delete the old file if too large?

### ISSUE THREAD

**Issue by sagarc03** [ray-x/guihua.lua#15]
https://github.com/ray-x/guihua.lua/blob/c0950d4611b3492b961b919fe46af995950d47a1/lua/guihua/log.lua#L54-60

This function should create a file in the cache if doesn't exits or delete old large file.

if the file does exit it will return nil which is affecting the initialization of, see below.

https://github.com/ray-x/navigator.lua/blob/2e96dcd327ce3b520e9569b7b619e6d8230e2736/lua/navigator/util.lua#L150-162

Current Fix, 

Manually create a file or delete old file in `~/.cache/nvim/` file name `gh.log`

**Comment by ray-x** [comment]
Thanks for submitting the issue. The issue was fixed.
