### ISSUE TITLE
[feature] add map : tabnew = '<C-t>',

### ISSUE THREAD

**Issue by MaiLunJiye** [ray-x/guihua.lua#19]
use `<c-t>` to open selected item in new tab.

**Comment by ray-x** [comment]
Please check if latest version works for you.

**Comment by MaiLunJiye** [comment]
I use `ray-x/navigator.lua`, and click `gr` to find some references. It will open a `guihua` window.
Then click `<c-t>`, the error `E73: tag stack empty` raise.
By the way, the output of `map <c-t>` in `guihua` window is `No mapping found`

**Comment by ray-x** [comment]
nmap is `t`,   imap `<c-t>`

**Comment by MaiLunJiye** [comment]
I think the operation logic should be unified.
For example: 
- in `ray-x/navigator.lua`, `gr` will open references window in normal mode.
In the window, `<c-s>` map to `split`, `<c-v>` map to `vsplit`, but `t` map to `tabnew`.
- `g0` will open `document_symbole` window in insert mode. And `<c-s>`, `<c-t>` will do nothing but `<c-t>` will `open in new tab`

I hope `<c-s>`, `<c-v>`, `<c-t>` are map to `split` , `vsplit` , `tabnew` in normal and insert mode

**Comment by ray-x** [comment]
sure, make sense. Repo updated.
