### ISSUE TITLE
Selected item index after filtering

### ISSUE THREAD

**Issue by pyrho** [ray-x/guihua.lua#2]
I'm playing around with guihua.lua but I'm having troubling figuring out how to retrieve the index of an element *after* fzy filtering has taken place.

The indices are always relative to the currently displayed results, but I need the absolute index of the selected element to show the preview for the correct item.

Here is a snippet (taken from the tests to reproduce what I'm talking about, run `:luafile %`, you must have files `/tmp/{hi,ho,ha}.txt` with some content in them.

Without filtering: the correct preview is displayed
Filter with `ho` (and then press arrow down to trigger the preview), the contents of 'hi.txt' is shown (should be `ho.txt`).
```lua
ocal ListView = require"guihua.listview"
local TextView = require"guihua.textview"
local lines = {
  "hi",
  "ho",
  "ha"
}
local data = {
  {
    filename  = "/tmp/hi.txt",
    uri = "file:///tmp/hi.txt",
  }, {
    filename  = "/tmp/ho.txt",
    uri = "file:///tmp/ho.txt",
  }, {
    filename  = "/tmp/ha.txt",
    uri = "file:///tmp/ha.txt",
  }
}

local function preview_uri(uri, line, offset_y)
  line = line or 1
  offset_y = offset_y or 6
  local loc = {targetUri = uri, targetRange = {start = {line = line}}}
  loc.targetRange["end"] = {line = line + 4}
  local n = tostring(os.time())
  local contents = {"local abc = 12", "local winid = " .. n, "print(winid)"}
  return TextView:new({
    loc = "top_center",
    rect = {height = #contents + 1, width = 90, pos_x = 0, pos_y = 7},
    -- data = display_data,
    -- data = contents,
    range = {
                ["end"] = {
                    character = 1,
                    line = 2
                },
                start = {
                    character = 1,
                    line = 0
                }
            },
    uri = uri,
    syntax = "lua"
  })
end

local on_move = function(pos)
  if pos == 0 then
    pos = 1
  end
  if pos > #data then
    print("[ERR] idx", pos, "length ", #data)
  end
  local l = data[pos]
  return preview_uri(l.uri)
end

local function test_preview()
   ListView:new({
    loc = "top_center",
    prompt = true,
    rect = {height = 4, width = 90},
    data = lines,
    on_move = on_move
  })
end

test_preview()
```

This is working fine in `navigator.lua`, so I must be missing something; I tried looking into the code but I failed to understand.

Any help appreciated, thanks !

ps: Great job on guihua and navigator btw !

**Comment by ray-x** [comment]
Thanks for trying this out.
I can see the problem in your code. 
For ListView, you passed in `lines` to data. the fzy will be apply to `lines`

I think you may need to 
1)
```lua
local data = {
  {filename = "/tmp/hi.txt", uri = "file:///tmp/hi.txt", text = "hi"},
  {filename = "/tmp/ho.txt", uri = "file:///tmp/ho.txt", text = "ho"},
  {filename = "/tmp/ha.txt", uri = "file:///tmp/ha.txt", text = "ha"}
}
```

2) 
```lua
   ListView:new({
    loc = "top_center",
    prompt = true,
    rect = {height = 4, width = 90},
    data = data,
    on_move = on_move
  })
```
3) use utils.fzy_idx to get the correct offset inside a fzy filtered list.

I created a new test file in guihua/tests/listview_fzy_test.lua and hope it helps.

**Comment by pyrho** [comment]
Thank you for your answer ! I just finished debugging my code and guihua's code and found out what the issue was.

At first it wasn't clear to me that you could pass an list of objects with the `text` property to be filtered on, it's clear now thanks.

I found a bug in the fzy version that's vendored in guihua, I created a PR [here](https://github.com/ray-x/guihua.lua/pull/3).
