### ISSUE TITLE
"missing argument: guifg=" when opening a hovering window

### ISSUE THREAD

**Issue by acetylen** [ray-x/guihua.lua#20]
When attempting to use any navigator.lua command that opens an overlay (like LspKeymaps, which I've used to try this out), guihua throws an error:

```
E5108: Error executing lua ...im/site/pack/packer/start/guihua.lua/lua/guihua/util.lua:152: Vim(highlight):E417: missing argument: guifg=
stack traceback:
        [C]: in function 'cmd'
        ...im/site/pack/packer/start/guihua.lua/lua/guihua/util.lua:152: in function 'selcolor'
        ...ite/pack/packer/start/guihua.lua/lua/guihua/listview.lua:41: in function 'initialize'
        ...im/site/pack/packer/start/guihua.lua/lua/middleclass.lua:135: in function 'new'
        .../start/navigator.lua/lua/navigator/lspclient/mapping.lua:490: in function 'get_keymaps_help'
        [string ":lua"]:1: in main chunk
```

This interestingly only happens once; after that the overlay box opens just fine and doesn't look weird in any way.

The error is here:
https://github.com/ray-x/guihua.lua/blob/a19ac4447021f21383fadd7a9e1fc150d0b67e1f/lua/guihua/util.lua#L147-L152

I'm assuming this has something to do with `if sel_gstr then`; since everything except `nil` and `false` is truthy, this would always be true, even if `sel_gstr == ""`. 
I use a light background with `notermguicolors`, so there's a chance that `sel_gstr` is empty.
Note that this is all just guesswork; setting `termguicolors` didn't help.

This is with NVIM v0.8.3, compiled with +acl +iconv +tui, so no gui support.

I'm using [my own colorscheme](https://github.com/acetylen/boring.nvim) without gui definitions, is this something I can fix by adding those?

**Comment by ray-x** [comment]
I pushed a change for it, please check if it works for you. Thanks!

**Comment by acetylen** [comment]
Yeah, that did it! Thanks for the quick response :)
