### ISSUE TITLE
Allow customizing icon choices

### ISSUE THREAD

**Issue by shaunduncan** [ray-x/guihua.lua#24]
I am using this library in conjunction with `go.nvim`. When using some of the features that use UI elements from this library, the icons that are used do not render correctly because I am not (nor do I want to) use a patched "nerd font". Currently I have to edit the plugin source directly to use alternative unicode symbols because there does not appear to be a way to customize these. It would be great if these were customizable. If there is a way to customize these and I have overlooked it, please let me know.

Thanks!

**Comment by ray-x** [comment]
What command in `go.nvim` failed to render `nerdfont`?

Is this what you need?

https://github.com/ray-x/guihua.lua/blob/3b3126ae87c254f6849e708549ba76c39e3f42f8/lua/guihua/panel.lua#L102

**Comment by ray-x** [comment]
Thanks for the suggestion. I pushed a PR for this.
You can config the icons to something like:
```lua
      require('guihua').setup({
        icons = {
          syntax = {
            namespace = '',
          }
        }
      })
```
refer to README for more details.

**Comment by shaunduncan** [comment]
I just tried and it works perfectly! Thank you!
