### ISSUE TITLE
 attempt to index upvalue 'guihua_term' (a nil value)

### ISSUE THREAD

**Issue by ttbug** [ray-x/guihua.lua#25]
Error with latest commit，revert to commit 3b3126ae87c254f6849，everything works well
neovim 0.10.0 latest dev version
![1715587843696](https://github.com/ray-x/guihua.lua/assets/24567096/ae339aea-a361-4741-b8d1-dc40631c0cdc)

**Comment by ray-x** [comment]
Would you share a bit more regarding how to reproduce?
seems you are running `GoTestFunc `. It is a bit strange I can not reproduce this issue.

**Comment by ray-x** [comment]
Would you check if the latest version fixed the issue? Thanks!

**Comment by ttbug** [comment]
> the latest version fixed the issue

 yes, it works well with the latest version.Thanks!!
